obj-m := $(TEST_NAME).o
$(TEST_NAME)-objs := $(TEST_NAME).rust.o

CARGO ?= cargo
TARGET ?= x86_64-unknown-none-linuxkernel

export c_flags
export UTEST

$(src)/target/$(TARGET)/debug/lib%.a: cargo_will_determine_dependencies
	cd $(src)/$(TEST_PATH); CARGO_TARGET_DIR=../target $(CARGO) build -Z build-std=core,alloc --target=$(TARGET) --features "krdma-test cow use_rc" --no-default-features
	cd $(src)/$(TEST_PATH); CARGO_TARGET_DIR=../target $(CARGO) doc --quiet -Z build-std=core,alloc --target=$(TARGET) --features "krdma-test cow use_rc" --no-default-features

.PHONY: cargo_will_determine_dependencies

quiet_cmd_rustld = LD [R]  $@
      cmd_rustld = $(LD) -r -o $@ --whole-archive $(real-prereqs)

$(obj)/%.rust.o: $(obj)/target/$(TARGET)/debug/lib%.a FORCE
	$(call if_changed,rustld)

targets += $(TEST_NAME).rust.o
